### ISSUE TITLE
Logo Missing

### ISSUE THREAD

**Issue by elysian-design** [clevett/Roll20-character-sheet-Shadowrun-5th-Edition#4]
The logo is currently missing. due to that the whole sheet is rendered with displaced elements.

it seems like https://raw.githubusercontent.com/Roll20/roll20-character-sheets/master/Shadowrun5thEdition/imgs//ShadowrunLogo.png returns a 404

**Comment by clevett** [comment]
Thanks for the report. I put in a hotfix request with Roll20 a few hours ago, https://github.com/Roll20/roll20-character-sheets/pull/8255
